services:
  database:
    image: postgres:15
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: joaountura
      POSTGRES_PASSWORD: joaountura@dev
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:8.0.3
    container_name: redis_auth
    ports:
      - "6379:6379"
    restart: unless-stopped


volumes:
  postgres_data:

