services:
  database:
    image: postgres:15
    container_name: auth_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: joaountura
      POSTGRES_PASSWORD: joaountura@dev
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:8.0.3
    container_name: redis_auth
    ports:
      - "6379:6379"
    restart: unless-stopped


  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"   # Modo DB-less
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"

    ports:
      - "8000:8000" # Porta Proxy (exposta para os clientes)
      - "8443:8443" # Proxy HTTPS
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API HTTPS
    volumes:
      - ./kong.yaml:/etc/kong/kong.yaml:ro
      - ../logs:/tmp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
      image: docker.elastic.co/kibana/kibana:8.14.0
      container_name: kibana
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      volumes:
        - kibana_data:/usr/share/kibana/data
      ports:
        - "5601:5601"
      depends_on:
        - elasticsearch

  logstash:
      image: docker.elastic.co/logstash/logstash:8.14.0
      container_name: logstash
      volumes:
        - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        - ../logs:/usr/share/logstash/logs
      ports:
        - "5000:5000"
      depends_on:
        - elasticsearch

networks:
    kong-net:
      driver: bridge

volumes:
  postgres_data:
  es_data:
  kibana_data:


